/**
 * @file local-command-row.test.ts
 * @description Tests for src/maestro-p/local-command-row.ts slash-command completion.
 *
 * A local slash command (`/compact`, `/clear`) writes no `end_turn` row, so its
 * output row is the only transcript signal that the command finished (issue
 * #1754). `localCommandOutput` must recognize both shapes claude writes that
 * row in, and must NOT fire on the `<command-name>` row that announces the
 * command, on the caveat meta row, or on ordinary prompt and tool rows.
 */

import { describe, it, expect } from 'vitest';

import { isSlashCommandPrompt, localCommandOutput } from '../../maestro-p/local-command-row';

// Rows copied from real claude 2.1.x transcripts.
const caveatRow = {
	type: 'user',
	isMeta: true,
	message: {
		role: 'user',
		content:
			'<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>',
	},
};

const compactNameRow = {
	type: 'user',
	sessionId: 'c1a71e04-b763-41d6-a900-88ddd7f476ac',
	message: {
		role: 'user',
		content:
			'<command-name>/compact</command-name>\n            <command-message>compact</command-message>\n            <command-args></command-args>',
	},
};

const compactOutputRow = {
	type: 'user',
	sessionId: 'c1a71e04-b763-41d6-a900-88ddd7f476ac',
	message: {
		role: 'user',
		content:
			'<local-command-stdout>\u001b[2mCompacted (ctrl+o to see full summary)\u001b[22m</local-command-stdout>',
	},
};

const systemOutputRow = {
	type: 'system',
	subtype: 'local_command',
	content: '<local-command-stdout>Goodbye!</local-command-stdout>',
	level: 'info',
};

const systemNameRow = {
	type: 'system',
	subtype: 'local_command',
	content:
		'<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>',
	level: 'info',
};

describe('localCommandOutput', () => {
	it('returns the ANSI-stripped output of a user-shaped output row', () => {
		expect(localCommandOutput(compactOutputRow)).toBe('Compacted (ctrl+o to see full summary)');
	});

	it('returns the output of a system local_command output row', () => {
		expect(localCommandOutput(systemOutputRow)).toBe('Goodbye!');
	});

	it('treats an empty output tag as a completed command with no text', () => {
		expect(
			localCommandOutput({
				type: 'system',
				subtype: 'local_command',
				content: '<local-command-stdout></local-command-stdout>',
			})
		).toBe('');
	});

	it('recognizes stderr output too', () => {
		expect(
			localCommandOutput({
				type: 'user',
				message: {
					role: 'user',
					content: '<local-command-stderr>Error: nope</local-command-stderr>',
				},
			})
		).toBe('Error: nope');
	});

	it('reads text blocks when the content is an array', () => {
		expect(
			localCommandOutput({
				type: 'user',
				message: {
					role: 'user',
					content: [{ type: 'text', text: '<local-command-stdout>Done</local-command-stdout>' }],
				},
			})
		).toBe('Done');
	});

	it('does not fire on the row that announces the command', () => {
		expect(localCommandOutput(compactNameRow)).toBeNull();
		expect(localCommandOutput(systemNameRow)).toBeNull();
	});

	it('does not fire on the caveat meta row', () => {
		expect(localCommandOutput(caveatRow)).toBeNull();
	});

	it('does not fire on a tool result that merely quotes the tag', () => {
		expect(
			localCommandOutput({
				type: 'user',
				message: {
					role: 'user',
					content: [
						{
							type: 'tool_result',
							content: '<local-command-stdout>x</local-command-stdout>',
						},
					],
				},
			})
		).toBeNull();
	});

	it('does not fire on assistant rows, compact boundaries, or junk', () => {
		expect(
			localCommandOutput({
				type: 'assistant',
				message: {
					content: [{ type: 'text', text: '<local-command-stdout>x</local-command-stdout>' }],
				},
			})
		).toBeNull();
		expect(
			localCommandOutput({
				type: 'system',
				subtype: 'compact_boundary',
				content: 'Conversation compacted',
			})
		).toBeNull();
		expect(localCommandOutput(null)).toBeNull();
		expect(localCommandOutput('row')).toBeNull();
	});
});

describe('isSlashCommandPrompt', () => {
	it('is true for a prompt the TUI runs as a slash command', () => {
		expect(isSlashCommandPrompt('/compact')).toBe(true);
		expect(isSlashCommandPrompt('  /clear is not a command here')).toBe(true);
	});

	it('is false for ordinary prompts and bash-mode input', () => {
		expect(isSlashCommandPrompt('please run /compact later')).toBe(false);
		expect(isSlashCommandPrompt('!ls')).toBe(false);
		expect(isSlashCommandPrompt('')).toBe(false);
	});
});
